<?php
$title = 'My products';
$this->headTitle($title);
?>   
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('product', array('action'=>'add'));?>">Agregar producto</a>
</p>

<table class="table">
	<tr>
		<th>Nombre</th>
		<th>Foto</th>
		<th>Descripción</th>
		<th>Precio</th>
		<th>Precio venta</th>
		<th>Cantidad</th>
		<th>&nbsp;</th>
	</tr>
	<?php 

	// EL escapeHtmls se usa por seguridad para evitar ataques

	foreach ($products as $product) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($product->name);?></td> 
		<td><?php echo $this->escapeHtml($product->photo);?></td>
		<td><?php echo $this->escapeHtml($product->detail);?></td>
		<td><?php echo $this->escapeHtml($product->price);?></td>
		<td><?php echo $this->escapeHtml($product->price_sale);?></td>
		<td><?php echo $this->escapeHtml($product->quantity);?></td>
		<td>
			<a href="<?php echo $this->url('product',
				array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
			<a href="<?php echo $this->url('product',
				array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>