
<?php $this->layout()->setVariable('total_items', $total_items); ?>
<?php $this->layout()->setVariable('og_url', $this->url('product', array('id' => $product->id))); ?>
<?php $this->layout()->setVariable('og_title', $product->name); ?>
<?php $this->layout()->setVariable('og_description', $product->detail); ?>
<?php $this->layout()->setVariable('og_image', $this->basePath('img/' . $product->photo)); ?>

<div id="content">
	<div class="container">

		<div class="col-md-12">
			<ul class="breadcrumb">
				<li><a href="#">Inicio</a>
				</li>
				<li><a href="#">Categoria</a>
				</li>
				<li><?php echo $this->escapeHtml($product->name); ?></li>
			</ul>

		</div>

<div class="col-md-12">

	<div class="row" id="productMain">
		<div class="col-sm-6">
			<div id="mainImage">
				<img src="http://localhost:8080/img/<?php echo $this->escapeHtml($product->photo); ?> " alt="" class="img-responsive">
			</div>

			<div class="ribbon sale">
				<div class="theribbon">SALE</div>
				<div class="ribbon-background"></div>
			</div>
			<!-- /.ribbon -->

			<div class="ribbon new">
				<div class="theribbon">NEW</div>
				<div class="ribbon-background"></div>
			</div>
			<!-- /.ribbon -->

		</div>
		<div class="col-sm-6">
			<div class="box">
				<h1 class="text-center"><?php echo $this->escapeHtml($product->name); ?> </h1>
				<p class="goToDescription"><a href="#details" class="scroll-to">Ver detalles </a>
				</p>
				<p class="price">$<?php echo $this->escapeHtml($product->price_sale); ?></p>

				<p class="text-center buttons">
					<a onclick="additem(<?php echo $this->escapeHtml($product->id); ?>)" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Agregar al carrito</a> 
					<a href="basket.html" class="btn btn-default"><i class="fa fa-heart"></i> Agregar a favoritos</a>
				</p>


			</div>

			<div class="row" id="thumbs">
				<div class="col-xs-4">
					<a href="<?php echo $this->basePath('img/' . $product->photo); ?>" class="thumb">
						<img src="<?php echo $this->basePath('img/' . $product->photo); ?>" alt="" class="img-responsive">
					</a>
				</div>
			</div>
		</div>

	</div>


	<div class="box" id="details">
	<div class="row">
	 <div class="col-md-6">
	 			<h4>Detalle del producto</h4>
			<p><?php echo $this->escapeHtml($product->detail); ?></p>
			<div class="ec-stars-wrapper">
			<a href="#" data-value="1" title="Votar con 1 estrellas">&#9733;</a>
			<a href="#" data-value="2" title="Votar con 2 estrellas">&#9733;</a>
			<a href="#" data-value="3" title="Votar con 3 estrellas">&#9733;</a>
			<a href="#" data-value="4" title="Votar con 4 estrellas">&#9733;</a>
			<a href="#" data-value="5" title="Votar con 5 estrellas">&#9733;</a>
			</div>
			<noscript>Califica el producto</noscript>
			<hr>
			<div class="social">
				<h4>Comparte con tus amigos</h4>
				<p><div class="fb-share-button" data-href="<?php echo $this->url('product',
                array('id' => $product->id));?>" data-layout="button_count" data-mobile-iframe="true"></div>
			</div>
	 </div>
		 <div class="col-md-6">
		  <div id="fb-root"></div>
		 <div class="fb-comments" data-href="" data-width="486" data-num-posts="3"></div>
		 </div>
	</div>
	</div>
	</div>
	<!-- /.col-md-9 -->
</div>
<!-- /.container -->
</div>
<script type="text/javascript">
    function additem(id) {
        var url = "<?php echo $this->url('info', array('action'=>'additem'));?>";
        $.ajax({
            type: "POST",
            url: url,
            data: {
                id: id,
            },
            success: function(response) {
            	alert(response.status);
            },
        });
    }
</script>
<script type="text/javascript">
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=205972183119645";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>