
<?php echo $this->escapeHtml($this->messages); ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('usr_name'));
echo $this->formRow($form->get('usr_password'));
echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
?>		
 | <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a> 
<?php
    } else {
        echo 'Not logged in';
    }
?>
<p>
	<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |  
	<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>

<div class="fade" 
data-animate="fadeInDown" id="login-modal" role="dialog" aria-labelledby="Login" aria-hidden="true">
<div class="modal-dialog modal-sm">

	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="Login">Inicio de sesión</h4>
		</div>
		<div class="modal-body">
			<?php echo $this->form()->openTag($form);?>
				<div class="form-group">
					<input type="text" name = "usr_name" class="form-control" id="email-modal" placeholder="Nombre de usuario">
				</div>
				<div class="form-group">
					<input type="password" name= "usr_password" class="form-control" id="password-modal" placeholder="Contraseña">
				</div>

				 <?php echo $this->formRow($form->get('rememberme'));?>
				 <br>
				<p class="text-center">
				<button type="submit" class="btn btn-primary" action="/auth/index/login" method = "post"><i class="fa fa-sign-in"></i> Ingresar</button>
			</p>
			<?php echo $this->form()->closeTag();?>
		<p>
		<center>  
	<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a></center>
	</p>
	
		<p class="text-center text-muted">¿No tienes cuenta?</p>

		<p class="text-center text-muted"><a href="/auth/registration/index"><strong>Registrarse</strong></a></p>
	</div>
</div>
</div>
</div>