<?php
$title = 'Productos';
$this->headTitle($title);
?>
<div class="container">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	<p>
		<a href="<?php echo $this->url('admin', array('action'=>'product-add'));?>">Agregar producto</a>
	</p>

	<table class="table">
		<tr>
			<th>Nombre</th>
			<th>Foto</th>
			<th>Descripción</th>
			<th>Precio</th>
			<th>Precio venta</th>
			<th>Cantidad</th>
			<th>&nbsp;</th>
		</tr>
		<?php 

	// EL escapeHtmls se usa por seguridad para evitar ataques

		foreach ($products as $product) : ?>
		<tr>
			<td><a href="<?php echo $this->url('product', array('id' => $product->id));?>"><?php echo $this->escapeHtml($product->name);?></a></td> 
			<td><?php echo $this->escapeHtml($product->photo);?></td>
			<td><?php echo $this->escapeHtml($product->detail);?></td>
			<td><?php echo $this->escapeHtml($product->price);?></td>
			<td><?php echo $this->escapeHtml($product->price_sale);?></td>
			<td><?php echo $this->escapeHtml($product->quantity);?></td>
			<td>
			<a href="<?php echo $this->url('admin',
				array('action'=>'product-edit', 'id' => $product->id));?>">Editar</a>
			<a href="<?php echo $this->url('admin',
				array('action'=>'product-delete', 'id' => $product->id));?>">Eliminar</a>
</td>
</tr>
<?php endforeach; ?>
</table>
</div>