<?php $this->layout()->setVariable('total_items', $total_items); ?>


    <div id="all">

        <div id="content">
            <div class="container">

                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Inicio</a>
                        </li>
                        <li>Carrito de compras</li>
                    </ul>
                </div>

                <div class="col-md-9" id="basket">

                    <div class="box">

                        <form method="post" action="checkout1.html">

                            <h1>Carrito de compras</h1>
<?php if($total_items > 0): ?>
                            <p class="text-muted">Actualmente tienes <?php echo $total_items ?> productos en tu carrito.</p>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Producto</th>
                                            <th>Cantidad</th>
                                            <th>Precio</th>
                                            <th colspan="2">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
<?php foreach($items as $key):?>
                                        <tr>
                                            <td>
                                                <a href="<?php echo $this->url('product',
                array('id' => $key['id']));?>">
                                                    <img src="http://localhost:8080/img/<?php echo $key['options']['img'];?>" alt="<?php echo $key['id']; ?>">
                                                </a>
                                            </td>
                                            <td><a href="<?php echo $this->url('product',
                array('id' => $key['id']));?>"><?php echo $key['name']; ?></a>
                                            </td>
                                            <td>
                                                <input type="number" value="<?php echo $key['qty']; ?>">
                                            </td>
                                            <td>$<?php echo $key['price']; ?></td>
                                            <td>$<?php echo $key['sub_total']; ?></td>
                                            <td><a href="#"><i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
<?php endforeach;?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="4">Total</th>
                                            <th colspan="2">$<?php echo $total['sub-total'];?></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
<?php else: ?>
<h4>El carrito de compras esta vacio</h4>
<?php endif;?>
                            <!-- /.table-responsive -->

                            <div class="box-footer">
                                <div class="pull-left">
                                    <a href="category.html" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                                </div>
                                <div class="pull-right">
                                    <button class="btn btn-default"><i class="fa fa-refresh"></i> Update basket</button>
                                    <button type="submit" class="btn btn-primary">Proceed to checkout <i class="fa fa-chevron-right"></i>
                                    </button>
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col-md-9 -->

                <div class="col-md-3">
                    <div class="box" id="order-summary">
                        <div class="box-header">
                            <h3>Total a pagar</h3>
                        </div>
                        <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Order subtotal</td>
                                        <th>$<?php echo $total['sub-total'];?></th>
                                    </tr>
                                    <tr>
                                        <td>Shipping and handling</td>
                                        <th>$<?php echo $total['vat'];?></th>
                                    </tr>
                                    <tr>
                                        <td>Tax</td>
                                        <th>$0.00</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th>$<?php echo $total['total'];?></th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>


                    <div class="box">
                        <div class="box-header">
                            <h4>Coupon code</h4>
                        </div>
                        <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
                        <form>
                            <div class="input-group">

                                <input type="text" class="form-control">

                                <span class="input-group-btn">

                    <button class="btn btn-primary" type="button"><i class="fa fa-gift"></i></button>

                    </span>
                            </div>
                            <!-- /input-group -->
                        </form>
                    </div>

                </div>
                <!-- /.col-md-3 -->

            </div>
            <!-- /.container -->
        </div>