<?php $this->layout()->setVariable('total_items', $total_items); 

function distance($lat1, $lon1, $lat2, $lon2, $unit) {

  $theta = $lon1 - $lon2;
  $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
  $dist = acos($dist);
  $dist = rad2deg($dist);
  $miles = $dist * 60 * 1.1515;
  $unit = strtoupper($unit);

  if ($unit == "K") {
    return ($miles * 1.609344);
} else if ($unit == "N") {
  return ($miles * 0.8684);
} else {
    return $miles;
}
}


function costoEnvio($country2,$city2){
    $precio =0;
    echo "Envio desde: ";
    $address1 = "Colombia+Bucaramanga";
    $region1="Colombia";
    $url = "http://maps.google.com/maps/api/geocode/json?address=$address1&sensor=false&region=$region1";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_PROXYPORT, 3128);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    $response = curl_exec($ch);
    curl_close($ch);
    $response_a = json_decode($response);
    $lat1 = $response_a->results[0]->geometry->location->lat;
    $long1 = $response_a->results[0]->geometry->location->lng;
    echo $address1;
    echo "<br>";


    echo "Envio hasta: ";
    $address2 = "$country2+$city2";
    $region2=$country2;
    $url = "http://maps.google.com/maps/api/geocode/json?address=$address2&sensor=false&region=$region2";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_PROXYPORT, 3128);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    $response = curl_exec($ch);
    curl_close($ch);
    $response_a = json_decode($response);
    $lat2 = $response_a->results[0]->geometry->location->lat;
    $long2 = $response_a->results[0]->geometry->location->lng;
    echo $address2;
    echo "<br>";

    echo "distancia: ";
    $distancia = distance($lat1, $long1,$lat2, $long2, "K");
    echo ((string)$distancia . " Kilometers<br>");
    echo "<br>";
    return $precio = $distancia*50;
    echo "Precio: $". $precio . " Pesos";
}

?>


<div id="all">

    <div id="content">
        <div class="container">

            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="<?php echo $this->url('home') ?>">Inicio</a>
                    </li>
                    <li>Carrito de compras</li>
                </ul>
            </div>

            <div class="col-md-9" id="basket">

                <div class="box">

                    <form method="post" action="checkout1.html">

                        <h1>Carrito de compras</h1>
                        <?php if($total_items > 0): ?>
                            <p class="text-muted">Actualmente tienes <?php echo $total_items ?> productos en tu carrito.</p>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Producto</th>
                                            <th>Cantidad</th>
                                            <th>Precio</th>
                                            <th colspan="2">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($items as $key):?>
                                            <tr>
                                                <td>
                                                    <a href="<?php echo $this->url('product',
                                                        array('id' => $key['id']));?>">
                                                        <img src="<?php echo $this->basePath('img/'. $key['options']['img']);?>" alt="<?php echo $key['id']; ?>">
                                                    </a>
                                                </td>
                                                <td><a href="<?php echo $this->url('product',
                                                    array('id' => $key['id']));?>"><?php echo $key['name']; ?></a>
                                                </td>
                                                <td>
                                                    <input type="number" value="<?php echo $key['qty']; ?>">
                                                </td>
                                                <td>$<?php echo $key['price']; ?></td>
                                                <td>$<?php echo $key['sub_total']; ?></td>
                                                <td><a href="#"><i class="fa fa-trash-o"></i></a>
                                                </td>
                                            </tr>
                                        <?php endforeach;?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="4">Total</th>
                                            <th colspan="2">$<?php echo $total['sub-total'];?></th>
                                            
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>

                            <h4>Checkout</h4>

                            <div class="form-group">
                                <label for="firstname">Firstname</label>
                                <input type="text" class="form-control" id="firstname">
                            </div>
                            <div class="form-group">
                                <label for="lastname">Lastname</label>
                                <input type="text" class="form-control" id="lastname">
                            </div>
                            <div class="form-group">
                                <label for="city">City</label>
                                <input type="text" name="city" class="form-control" id="city">
                            </div>
                            <div class="form-group">
                                <label for="country">Country</label>
                                <input class="form-control" name="city" id="country"></input>
                            </div>
                        <?php else: ?>
                            <h4>El carrito de compras esta vacio</h4>
                        <?php endif;?>
                        <!-- /.table-responsive -->

                        <div class="box-footer">
                            <div class="pull-left">
                                <a href="category.html" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                            </div>
                            <div class="pull-right">
                                <input class="btn btn-default" type="button" onclick="costoEnvio()"><i class="fa fa-refresh"></i></input>
                                <!--//BOTON DE CHECKOUT-->
                                <a class='btn btn-success' href="<?php echo $this->url('payments-create'); echo '?total_pagar='; echo $total['sub-total']+$precio   ?>">
                                    <?php echo $this->translate("CheckOut"); ?>
                                </a>


                            </button>
                        </div>
                    </div>

                </form>

            </div>
            <!-- /.box -->

        </div>
        <!-- /.col-md-9 -->

        <div class="col-md-3">
            <div class="box" id="order-summary">
                <div class="box-header">
                    <h3>Total a pagar</h3>
                </div>
                <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Order subtotal</td>
                                <th>$<?php echo $total['sub-total'];?></th>
                            </tr>
                            <tr>
                                <td>Shipping</td>
                                <th>$<?php echo $precio;?></th>
                            </tr>
                            <tr class="total">
                                <td>Total</td>
                                <th>$<?php echo $total['sub-total']+$precio;?></th>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>

        </div>
        <!-- /.col-md-3 -->

    </div>
    <!-- /.container -->
</div>